from datetime import date
from code.src.models import (
    RequestContext,
    UserFinancialProfile,
    PlanEvaluation,
    SpendingChange,
    Decision,
)


def format_amount(amt: float) -> str:
    """Formats monetary amounts preserving two decimal places for fractional amounts and no decimals for integers."""
    rounded = round(amt, 2)
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{amt:.2f}"


def serialize_payment_plan(plan_eval: PlanEvaluation | None) -> str:
    if not plan_eval or plan_eval.plan.method == "not_recommended" or not plan_eval.plan.payments:
        return "none"

    sorted_payments = sorted(plan_eval.plan.payments, key=lambda p: p.payment_date)
    chunks = [f"{p.payment_date.isoformat()}:{format_amount(p.amount)}" for p in sorted_payments]
    return "|".join(chunks)


def serialize_spending_changes(changes: list[SpendingChange]) -> str:
    if not changes:
        return "none"
    chunks = []
    for c in changes:
        if c.action == "stop":
            chunks.append(f"stop:{c.event_id}")
        elif c.action == "reduce":
            chunks.append(f"reduce_to:{c.event_id}:{format_amount(c.new_amount or 0.0)}")
    return "|".join(chunks)


def rank_eligible_plans(
    evaluations: list[PlanEvaluation],
    request: RequestContext,
    has_spending_changes: bool,
) -> list[PlanEvaluation]:
    """
    Ranks eligible plans using the official challenge tie-breaker rules:
    1. Complete full request by desired_completion_date (handled by eligible=True).
    2. Require no spending changes (handled at set selection level).
    3. Minimize total amount paid (total_payable_amount).
    4. Start payment earlier (first payment date).
    5. Use fewer payments (len(payments)).
    6. Lowest payment_option_id as final tie-breaker.
    """
    eligible = [ev for ev in evaluations if ev.eligible]
    if not eligible:
        return []

    def sort_key(ev: PlanEvaluation):
        plan = ev.plan
        first_date = plan.payments[0].payment_date if plan.payments else request.request_date
        total_paid = plan.total_amount
        num_payments = len(plan.payments)
        opt_id = plan.payment_option_id or "zzzzzz"
        return (total_paid, first_date, num_payments, opt_id)

    eligible.sort(key=sort_key)
    return eligible


def select_final_decision(
    request: RequestContext,
    profile: UserFinancialProfile,
    baseline_safe_amount: float,
    earliest_full_payment_date: date | None,
    base_evaluations: list[PlanEvaluation],
    optimized_evaluations: list[PlanEvaluation],
    applied_changes: list[SpendingChange],
) -> Decision:
    """
    Pure deterministic selection of the final decision and OutputRow fields.
    """
    # 1. Check if baseline full payment today is safe and allowed
    full_today_evals = [
        ev for ev in base_evaluations
        if ev.plan.method == "full_payment"
        and ev.plan.payments
        and ev.plan.payments[0].payment_date == request.request_date
        and ev.eligible
    ]
    if full_today_evals:
        chosen_eval = full_today_evals[0]
        return Decision(
            request_id=request.request_id,
            amount_safe_to_pay=request.requested_amount,
            affordability_status="affordable_now",
            recommended_payment_method="full_payment",
            payment_plan=serialize_payment_plan(chosen_eval),
            earliest_date_for_full_payment=request.request_date.isoformat(),
            spending_changes_needed="none",
            decision_explanation="",  # Will be generated by explanation generator
        )

    # 2. Check other eligible base plans (installments, partial_payment)
    ranked_base = rank_eligible_plans(base_evaluations, request, has_spending_changes=False)
    # Prefer immediate options (installments / partial_payment) over wait if eligible
    immediate_base = [ev for ev in ranked_base if ev.plan.method in ("installments", "partial_payment")]
    if immediate_base:
        chosen_eval = immediate_base[0]
        return Decision(
            request_id=request.request_id,
            amount_safe_to_pay=baseline_safe_amount,
            affordability_status="affordable_with_plan",
            recommended_payment_method=chosen_eval.plan.method,
            payment_plan=serialize_payment_plan(chosen_eval),
            earliest_date_for_full_payment=earliest_full_payment_date.isoformat() if earliest_full_payment_date else "",
            spending_changes_needed="none",
            decision_explanation="",
        )

    # 3. Check if spending changes make a plan safe (affordable_with_plan)
    if applied_changes:
        ranked_opt = rank_eligible_plans(optimized_evaluations, request, has_spending_changes=True)
        if ranked_opt:
            chosen_eval = ranked_opt[0]
            return Decision(
                request_id=request.request_id,
                amount_safe_to_pay=baseline_safe_amount,  # Must remain baseline capacity (Issue 7)
                affordability_status="affordable_with_plan",
                recommended_payment_method=chosen_eval.plan.method,
                payment_plan=serialize_payment_plan(chosen_eval),
                earliest_date_for_full_payment=earliest_full_payment_date.isoformat() if earliest_full_payment_date else "",
                spending_changes_needed=serialize_spending_changes(applied_changes),
                decision_explanation="",
            )

    # 4. Check wait option (affordable_later)
    wait_evals = [ev for ev in base_evaluations if ev.plan.method == "wait" and ev.eligible]
    if wait_evals and earliest_full_payment_date is not None and earliest_full_payment_date <= request.desired_completion_date:
        chosen_eval = wait_evals[0]
        return Decision(
            request_id=request.request_id,
            amount_safe_to_pay=baseline_safe_amount,
            affordability_status="affordable_later",
            recommended_payment_method="wait",
            payment_plan=serialize_payment_plan(chosen_eval),
            earliest_date_for_full_payment=earliest_full_payment_date.isoformat(),
            spending_changes_needed="none",
            decision_explanation="",
        )

    # 5. Not affordable fallback
    return Decision(
        request_id=request.request_id,
        amount_safe_to_pay=baseline_safe_amount,
        affordability_status="not_affordable",
        recommended_payment_method="not_recommended",
        payment_plan="none",
        earliest_date_for_full_payment="",
        spending_changes_needed="none",
        decision_explanation="",
    )
