#!/bin/bash
# Create submission files for HackerRank Orchestrate

echo "Creating submission package..."

# Check if output.csv exists
if [ ! -f "output.csv" ]; then
    echo "⚠️  Error: output.csv not found!"
    echo "Please run ./run.sh first to generate predictions."
    exit 1
fi

# Check if log.txt exists
if [ ! -f "log.txt" ]; then
    echo "⚠️  Warning: log.txt not found!"
    echo "This file should be auto-generated by your AI assistant."
fi

# Create code.zip
echo "Creating code.zip..."
cd code
zip -r ../code.zip . -x "*.pyc" -x "__pycache__/*" -x ".DS_Store" -x "*.swp"
cd ..

echo ""
echo "✅ Submission package created!"
echo ""
echo "📦 Files ready for submission:"
echo "   1. code.zip - Your solution code"
echo "   2. output.csv - Predictions for all requests"
echo "   3. log.txt - Chat transcript (if available)"
echo ""
echo "📤 Submit these files at:"
echo "   https://www.hackerrank.com/contests/hackerrank-orchestrate-september26/challenges/buy-or-wait/submission"
